import type { MetadataRoute } from "next";
import { prisma } from "@/lib/prisma";

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://renttools.io";

// Force per-request rendering. ISR (revalidate=N) wasn't enough — the
// build still pre-renders sitemap() once on the GH Actions runner where
// there's no DB, ships an empty snapshot, and serves that for the first
// `revalidate` window. force-dynamic skips the build-time render
// entirely, so /sitemap.xml is always generated by the droplet against
// the live DB. Crawl traffic on a sitemap is a few hits per day —
// running one Prisma query each is fine.
export const dynamic = "force-dynamic";

/**
 * Sitemap. Static marketing pages + per-post + per-tag entries pulled
 * live from the DB. `lastModified` = `updatedAt` when set, otherwise
 * `publishedAt` — Google uses this signal to decide whether to recrawl,
 * so we want it to actually move when an editor saves a post.
 *
 * Drafts and future-scheduled posts are filtered out so the public
 * sitemap matches what /blog actually surfaces.
 */
export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const now = new Date();

  const staticEntries: MetadataRoute.Sitemap = [
    { url: `${SITE_URL}/`, lastModified: now, changeFrequency: "weekly", priority: 1.0 },
    { url: `${SITE_URL}/signup`, lastModified: now, changeFrequency: "monthly", priority: 0.8 },
    { url: `${SITE_URL}/login`, lastModified: now, changeFrequency: "monthly", priority: 0.6 },
    { url: `${SITE_URL}/blog`, lastModified: now, changeFrequency: "daily", priority: 0.9 },
    { url: `${SITE_URL}/terms`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
    { url: `${SITE_URL}/privacy`, lastModified: now, changeFrequency: "yearly", priority: 0.3 },
  ];

  // Below this many posts a tag page is "thin content" — Google ranks it
  // as low-value duplicate-of-the-blog-index and that drag spreads to the
  // sitemap. Below the threshold the tag still works as navigation, but
  // we keep it off the sitemap and emit a `noindex` meta on the page
  // (see app/blog/tag/[slug]/page.tsx). 3 is the line every major
  // SEO post-mortem (Moz, Ahrefs) settles on for blog taxonomies.
  const TAG_INDEX_MIN_POSTS = 3;

  let postEntries: MetadataRoute.Sitemap = [];
  let tagEntries: MetadataRoute.Sitemap = [];
  try {
    const posts = await prisma.blogPost.findMany({
      where: {
        locale: "en",
        status: "published",
        publishedAt: { lte: now },
      },
      select: { slug: true, tagsJson: true, publishedAt: true, updatedAt: true },
      orderBy: { publishedAt: "desc" },
    });
    postEntries = posts.map((p) => ({
      url: `${SITE_URL}/blog/${p.slug}`,
      lastModified: p.updatedAt ?? p.publishedAt ?? now,
      changeFrequency: "monthly" as const,
      priority: 0.7,
    }));

    // Count posts-per-tag in code rather than running N+1 queries — the
    // post list is already in memory and tag-counts on a small blog
    // (<200 posts) are well under any cardinality concern.
    const tagPostCount = new Map<string, number>();
    const tagLastMod = new Map<string, Date>();
    for (const p of posts) {
      let tagSlugs: string[] = [];
      try {
        const arr = JSON.parse(p.tagsJson) as unknown;
        if (Array.isArray(arr)) tagSlugs = arr.filter((t): t is string => typeof t === "string");
      } catch {
        /* malformed row — skip its tags rather than crash */
      }
      const lastMod = p.updatedAt ?? p.publishedAt ?? now;
      for (const slug of tagSlugs) {
        tagPostCount.set(slug, (tagPostCount.get(slug) ?? 0) + 1);
        const prev = tagLastMod.get(slug);
        if (!prev || lastMod > prev) tagLastMod.set(slug, lastMod);
      }
    }

    const tags = await prisma.blogTag.findMany({
      where: { locale: "en" },
      select: { slug: true, createdAt: true },
    });
    tagEntries = tags
      .filter((t) => (tagPostCount.get(t.slug) ?? 0) >= TAG_INDEX_MIN_POSTS)
      .map((t) => ({
        url: `${SITE_URL}/blog/tag/${encodeURIComponent(t.slug)}`,
        lastModified: tagLastMod.get(t.slug) ?? t.createdAt,
        changeFrequency: "weekly" as const,
        priority: 0.5,
      }));
  } catch (err) {
    // DB unavailable at build time? Ship the static entries and let the
    // next regeneration pick the dynamic ones up. Better than 500-ing the
    // /sitemap.xml endpoint and hurting crawl frequency.
    console.warn("sitemap: failed to load blog rows", err);
  }

  return [...staticEntries, ...postEntries, ...tagEntries];
}
